# Generated by Django 6.0.7 on 2026-09-30 19:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Akaunti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namba', models.CharField(blank=True, max_length=16, unique=True)),
                ('aina', models.CharField(choices=[('hifadhi', 'Hifadhi'), ('biashara', 'Biashara')], default='hifadhi', max_length=20)),
                ('salio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('imefunguliwa', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imefunguliwa'],
            },
        ),
        migrations.CreateModel(
            name='Wateja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=120, verbose_name='Jina kamili')),
                ('simu', models.CharField(max_length=20, unique=True, verbose_name='Simu')),
                ('barua_pepe', models.EmailField(blank=True, max_length=254, verbose_name='Barua pepe')),
                ('anwani', models.CharField(blank=True, max_length=200, verbose_name='Anwani')),
                ('imesajiliwa', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['jina'],
            },
        ),
        migrations.CreateModel(
            name='Miamala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aina', models.CharField(choices=[('kuweka', 'Kuweka'), ('kutoa', 'Kutoa')], max_length=10)),
                ('kiasi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('maelezo', models.CharField(blank=True, max_length=200)),
                ('tarehe', models.DateTimeField(auto_now_add=True)),
                ('akaunti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miamala', to='huduma.akaunti')),
                ('alifanya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='miamala', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tarehe'],
            },
        ),
        migrations.CreateModel(
            name='Mkopo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kiasi', models.DecimalField(decimal_places=2, max_digits=12)),
                ('riba_asilimia', models.DecimalField(decimal_places=2, default=10, max_digits=5)),
                ('salio', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('hali', models.CharField(choices=[('hai', 'Hai'), ('umelipa', 'Umelipa')], default='hai', max_length=10)),
                ('tarehe', models.DateTimeField(auto_now_add=True)),
                ('wateja', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mikopo', to='huduma.wateja')),
            ],
            options={
                'ordering': ['-tarehe'],
            },
        ),
        migrations.AddField(
            model_name='akaunti',
            name='wateja',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='akaunti', to='huduma.wateja'),
        ),
    ]
