# Generated by Django 6.0.7 on 2026-09-30 23:47

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Barua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namba', models.CharField(blank=True, max_length=30, unique=True)),
                ('aina', models.CharField(choices=[('ingia', 'Imeingia'), ('toka', 'Imetoka')], default='ingia', max_length=10)),
                ('kichwa', models.CharField(max_length=200)),
                ('mhusika', models.CharField(help_text='Ofisi/mtu anayetumiwa', max_length=120)),
                ('tarehe', models.DateField(default=datetime.date.today)),
                ('faili', models.FileField(blank=True, upload_to='barua/%Y/')),
                ('imerejistrwa', models.DateTimeField(auto_now_add=True)),
                ('aliwasilisha', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='barua', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-tarehe', '-imerejistrwa'],
            },
        ),
        migrations.CreateModel(
            name='Maombi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aina', models.CharField(choices=[('likizo', 'Likizo'), ('kuagiza', 'Kuagiza vifaa'), ('fedha', 'Maombi ya fedha')], max_length=20)),
                ('maelezo', models.TextField(verbose_name='Maelezo')),
                ('hali', models.CharField(choices=[('rasimu', 'Rasimu'), ('imewasilishwa', 'Imewasilishwa'), ('imeidhinishwa', 'Imeidhinishwa'), ('imekataliwa', 'Imekataliwa')], default='rasimu', max_length=20)),
                ('maoni', models.CharField(blank=True, max_length=300)),
                ('imewasilishwa', models.DateTimeField(blank=True, null=True)),
                ('imeamuliwa', models.DateTimeField(blank=True, null=True)),
                ('imetengenezwa', models.DateTimeField(auto_now_add=True)),
                ('mhusika', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maombi_yangu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imetengenezwa'],
            },
        ),
        migrations.CreateModel(
            name='Kumbukumbu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mada', models.CharField(max_length=200)),
                ('maelezo', models.CharField(blank=True, max_length=300)),
                ('tarehe', models.DateTimeField(auto_now_add=True)),
                ('alifanya', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kumbukumbu_angu', to=settings.AUTH_USER_MODEL)),
                ('maombi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kumbukumbu', to='kazi.maombi')),
            ],
            options={
                'ordering': ['-tarehe'],
            },
        ),
    ]
