# Generated by Django 6.0.7 on 2026-10-01 02:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lebo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=40, unique=True)),
            ],
            options={
                'ordering': ['jina'],
            },
        ),
        migrations.CreateModel(
            name='Bidhaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina', models.CharField(max_length=120)),
                ('maelezo', models.TextField(blank=True)),
                ('bei', models.DecimalField(decimal_places=0, max_digits=10)),
                ('stoo', models.PositiveIntegerField(default=0)),
                ('imeongezwa', models.DateTimeField(auto_now_add=True)),
                ('imebadilishwa', models.DateTimeField(auto_now=True)),
                ('lebo', models.ManyToManyField(blank=True, related_name='bidhaa', to='biashara.lebo')),
            ],
            options={
                'ordering': ['jina'],
            },
        ),
        migrations.CreateModel(
            name='Oda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(blank=True, max_length=20, unique=True)),
                ('hali', models.CharField(choices=[('tarajiwa', 'Inasubiri malipo'), ('imekulipwa', 'Imekulipwa'), ('imefutwa', 'Imefutwa')], default='tarajiwa', max_length=15)),
                ('njia', models.CharField(choices=[('mpesa', 'M-Pesa'), ('taslimu', 'Taslimu')], max_length=10)),
                ('simu', models.CharField(blank=True, max_length=15)),
                ('jumla', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('imeandikwa', models.DateTimeField(auto_now_add=True)),
                ('mtumiaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oda', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-imeandikwa'],
            },
        ),
        migrations.CreateModel(
            name='OdaBidhaa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jina_la_bidhaa', models.CharField(max_length=120)),
                ('bei', models.DecimalField(decimal_places=0, max_digits=10)),
                ('idadi', models.PositiveIntegerField()),
                ('bidhaa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mauzo', to='biashara.bidhaa')),
                ('oda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vipengele', to='biashara.oda')),
            ],
        ),
        migrations.CreateModel(
            name='Kipengele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idadi', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('bidhaa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kikapuni', to='biashara.bidhaa')),
                ('mtumiaji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kikapu', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('bidhaa', 'mtumiaji'), name='kipekee_kwa_mtumiaji')],
            },
        ),
    ]
